TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += mecfrf.db
DATA += mecfrf.proto

#=======================================
include $(TOP)/configure/RULES
